In [1]:
import pandas as pd
import numpy as np

In [2]:
ds=pd.read_csv('/kaggle/input/liver-cirrhosis-stage-classification/liver_cirrhosis.csv')

In [3]:
ds.head()

N_Days Status     Drug    Age Sex Ascites Hepatomegaly Spiders Edema  \
0    2221      C  Placebo  18499   F       N            Y       N     N   
1    1230      C  Placebo  19724   M       Y            N       Y     N   
2    4184      C  Placebo  11839   F       N            N       N     N   
3    2090      D  Placebo  16467   F       N            N       N     N   
4    2105      D  Placebo  21699   F       N            Y       N     N   

   Bilirubin  Cholesterol  Albumin  Copper  Alk_Phos    SGOT  Tryglicerides  \
0        0.5        149.0     4.04   227.0     598.0   52.70           57.0   
1        0.5        219.0     3.93    22.0     663.0   45.00           75.0   
2        0.5        320.0     3.54    51.0    1243.0  122.45           80.0   
3        0.7        255.0     3.74    23.0    1024.0   77.50           58.0   
4        1.9        486.0     3.54    74.0    1052.0  108.50          109.0   

   Platelets  Prothrombin  Stage  
0      256.0          9.9      1  
1      220.0         10.8      2  
2      225.0         10.0      2  
3      151.0         10.2      2  
4      151.0         11.5      1

In [4]:
ds.tail()

N_Days Status             Drug    Age Sex Ascites Hepatomegaly Spiders  \
24995    3584      D  D-penicillamine  23612   F       N            N       N   
24996    3584      D  D-penicillamine  23612   F       N            N       N   
24997     971      D  D-penicillamine  16736   F       N            Y       Y   
24998    3707      C  D-penicillamine  16990   F       N            Y       N   
24999    3707      C  D-penicillamine  16990   F       N            Y       N   

      Edema  Bilirubin  Cholesterol  Albumin  Copper  Alk_Phos    SGOT  \
24995     N        0.8   231.000000     3.87   173.0    9009.8  127.71   
24996     N        0.8   231.000000     3.87   173.0    9009.8  127.71   
24997     Y        5.1   369.510563     3.23    18.0     790.0  179.80   
24998     N        0.8   315.000000     4.24    13.0    1637.0  170.50   
24999     N        0.8   315.000000     4.24    13.0    1637.0  170.50   

       Tryglicerides  Platelets  Prothrombin  Stage  
24995      96.000000      295.0         11.0      2  
24996      96.000000      295.0         11.0      2  
24997     124.702128      104.0         13.0      3  
24998      70.000000      426.0         10.9      2  
24999      70.000000      426.0         10.9      2

In [5]:
ds.describe()

N_Days           Age     Bilirubin   Cholesterol       Albumin  \
count  25000.000000  25000.000000  25000.000000  25000.000000  25000.000000   
mean    1887.117040  18495.877080      3.402644    372.331471      3.486578   
std     1091.690918   3737.596616      4.707491    193.668452      0.380488   
min       41.000000   9598.000000      0.300000    120.000000      1.960000   
25%     1080.000000  15694.000000      0.800000    275.000000      3.290000   
50%     1680.000000  18499.000000      1.300000    369.510563      3.510000   
75%     2576.000000  20955.000000      3.400000    369.510563      3.750000   
max     4795.000000  28650.000000     28.000000   1775.000000      4.640000   

             Copper      Alk_Phos          SGOT  Tryglicerides     Platelets  \
count  25000.000000  25000.000000  25000.000000   25000.000000  25000.000000   
mean     100.184663   1995.675597    123.166345     123.822548    256.007337   
std       73.184840   1798.885660     47.747616      52.786350     98.679006   
min        4.000000    289.000000     26.350000      33.000000     62.000000   
25%       52.000000   1032.000000     92.000000      92.000000    189.000000   
50%       97.648387   1828.000000    122.556346     124.702128    251.000000   
75%      107.000000   1982.655769    134.850000     127.000000    311.000000   
max      588.000000  13862.400000    457.250000     598.000000    721.000000   

        Prothrombin        Stage  
count  25000.000000  25000.00000  
mean      10.734549      2.00116  
std        0.904436      0.81387  
min        9.000000      1.00000  
25%       10.000000      1.00000  
50%       10.600000      2.00000  
75%       11.100000      3.00000  
max       18.000000      3.00000

In [6]:
ds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25000 entries, 0 to 24999
Data columns (total 19 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   N_Days         25000 non-null  int64  
 1   Status         25000 non-null  object 
 2   Drug           25000 non-null  object 
 3   Age            25000 non-null  int64  
 4   Sex            25000 non-null  object 
 5   Ascites        25000 non-null  object 
 6   Hepatomegaly   25000 non-null  object 
 7   Spiders        25000 non-null  object 
 8   Edema          25000 non-null  object 
 9   Bilirubin      25000 non-null  float64
 10  Cholesterol    25000 non-null  float64
 11  Albumin        25000 non-null  float64
 12  Copper         25000 non-null  float64
 13  Alk_Phos       25000 non-null  float64
 14  SGOT           25000 non-null  float64
 15  Tryglicerides  25000 non-null  float64
 16  Platelets      25000 non-null  float64
 17  Prothrombin    25000 non-null  float64
 18  Stage 

In [7]:
ds.isnull()

N_Days  Status   Drug    Age    Sex  Ascites  Hepatomegaly  Spiders  \
0       False   False  False  False  False    False         False    False   
1       False   False  False  False  False    False         False    False   
2       False   False  False  False  False    False         False    False   
3       False   False  False  False  False    False         False    False   
4       False   False  False  False  False    False         False    False   
...       ...     ...    ...    ...    ...      ...           ...      ...   
24995   False   False  False  False  False    False         False    False   
24996   False   False  False  False  False    False         False    False   
24997   False   False  False  False  False    False         False    False   
24998   False   False  False  False  False    False         False    False   
24999   False   False  False  False  False    False         False    False   

       Edema  Bilirubin  Cholesterol  Albumin  Copper  Alk_Phos   SGOT  \
0      False      False        False    False   False     False  False   
1      False      False        False    False   False     False  False   
2      False      False        False    False   False     False  False   
3      False      False        False    False   False     False  False   
4      False      False        False    False   False     False  False   
...      ...        ...          ...      ...     ...       ...    ...   
24995  False      False        False    False   False     False  False   
24996  False      False        False    False   False     False  False   
24997  False      False        False    False   False     False  False   
24998  False      False        False    False   False     False  False   
24999  False      False        False    False   False     False  False   

       Tryglicerides  Platelets  Prothrombin  Stage  
0              False      False        False  False  
1              False      False        False  False  
2              False      False        False  False  
3              False      False        False  False  
4              False      False        False  False  
...              ...        ...          ...    ...  
24995          False      False        False  False  
24996          False      False        False  False  
24997          False      False        False  False  
24998          False      False        False  False  
24999          False      False        False  False  

[25000 rows x 19 columns]

In [8]:
ds.isna().sum()

N_Days           0
Status           0
Drug             0
Age              0
Sex              0
Ascites          0
Hepatomegaly     0
Spiders          0
Edema            0
Bilirubin        0
Cholesterol      0
Albumin          0
Copper           0
Alk_Phos         0
SGOT             0
Tryglicerides    0
Platelets        0
Prothrombin      0
Stage            0
dtype: int64

In [9]:
from sklearn.preprocessing import OneHotEncoder

In [10]:
categorical_columns=ds.select_dtypes(include=['object']).columns.tolist()

In [11]:
encoder=OneHotEncoder(sparse_output=False)

In [12]:
one_hot_encoded=encoder.fit_transform(ds[categorical_columns])
one_hot_df=pd.DataFrame(one_hot_encoded,columns=encoder.get_feature_names_out(categorical_columns))

In [13]:
ds_encoded=pd.concat([ds,one_hot_df],axis=1)
ds_encoded=ds_encoded.drop(categorical_columns,axis=1)

In [14]:
print(ds_encoded.head())

   N_Days    Age  Bilirubin  Cholesterol  Albumin  Copper  Alk_Phos    SGOT  \
0    2221  18499        0.5        149.0     4.04   227.0     598.0   52.70   
1    1230  19724        0.5        219.0     3.93    22.0     663.0   45.00   
2    4184  11839        0.5        320.0     3.54    51.0    1243.0  122.45   
3    2090  16467        0.7        255.0     3.74    23.0    1024.0   77.50   
4    2105  21699        1.9        486.0     3.54    74.0    1052.0  108.50   

   Tryglicerides  Platelets  ...  Sex_M  Ascites_N  Ascites_Y  Hepatomegaly_N  \
0           57.0      256.0  ...    0.0        1.0        0.0             0.0   
1           75.0      220.0  ...    1.0        0.0        1.0             1.0   
2           80.0      225.0  ...    0.0        1.0        0.0             1.0   
3           58.0      151.0  ...    0.0        1.0        0.0             1.0   
4          109.0      151.0  ...    0.0        1.0        0.0             0.0   

   Hepatomegaly_Y  Spiders_N  Spiders_

In [15]:
colx=ds_encoded.columns.tolist()
colx.remove('Stage')

In [18]:
x = ds_encoded[colx].values
y=ds_encoded["Stage"].values

del colx

In [19]:
from sklearn.model_selection import train_test_split
X_train,x_test,Y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [21]:
from sklearn.preprocessing import StandardScaler
sc_X=StandardScaler()
X_train=sc_X.fit_transform(X_train)
x_test=sc_X.transform(x_test)

In [22]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [23]:
knn=KNeighborsClassifier(n_neighbors=3,metric='minkowski',p=1)
knn.fit(X_train,Y_train)
y_pred=knn.predict(x_test)

In [24]:
accuracy=accuracy_score(y_test,y_pred)
print('KNN model accuracy:',accuracy)
cm=confusion_matrix(y_test,y_pred)
print(cm)

KNN model accuracy: 0.9204
[[1451  102   39]
 [ 105 1549   56]
 [  40   56 1602]]


In [26]:
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

           1       0.91      0.91      0.91      1596
           2       0.91      0.91      0.91      1707
           3       0.94      0.94      0.94      1697

    accuracy                           0.92      5000
   macro avg       0.92      0.92      0.92      5000
weighted avg       0.92      0.92      0.92      5000

